global:
  resolve_timeout: 5m

inhibit_rules:
- equal:
  - namespace
  - alertname
  source_matchers:
  - severity = critical
  target_matchers:
  - severity =~ warning|info

- equal:
  - namespace
  - alertname
  source_matchers:
  - severity = warning
  target_matchers:
  - severity = info

- equal:
  - namespace
  source_matchers:
  - alertname = InfoInhibitor
  target_matchers:
  - severity = info

route:
  group_by:
  - namespace
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: Default

  routes:
  - matchers:
    - alertname = Watchdog
    receiver: Watchdog

  - matchers:
    - alertname = InfoInhibitor
    receiver: "null"

  - matchers:
    - severity = critical
    receiver: Critical

receivers:
- name: Default

- name: Watchdog

- name: Critical
  pagerduty_configs:
  - routing_key: e185649a4bf14600d00ff591aecbce5f
    description: "{{ .CommonAnnotations.summary }}"
    severity: critical

- name: "null"
