apiVersion: v1
kind: Pod
metadata:
  name: memory-hog
  namespace: production
  labels:
    app: memory-hog
spec:
  containers:
  - name: memory-hog
    image: polinux/stress
    resources:
      limits:
        memory: "500Mi"
      requests:
        memory: "200Mi"
    command:
      - stress
    args:
      - "--vm"
      - "1"
      - "--vm-bytes"
      - "400M"
      - "--vm-hang"
      - "1"

